/**
 * iPhone device configurations — verified against Apple specs (July 2026).
 * Updated with pixel-accurate Dynamic Island pill cutouts and proportion ratios.
 */
import { DeviceModel } from './types';

export const IPHONE_DEVICES: readonly DeviceModel[] = [
  // --- iPhone 17 line (Dynamic Island) ---
  {
    id: 'iphone-17-pro-max',
    category: 'iphone',
    displayName: 'iPhone 17 Pro Max',
    bezelStyle: 'dynamic-island',
    resolution: { width: 1320, height: 2868 },
    aspectRatio: 1320 / 2868,
    cornerRadiusPct: 12,
    cutout: { widthPct: 28, heightPct: 3.4, topOffsetPct: 2.2 },
    generation: '17',
  },
  {
    id: 'iphone-17-pro',
    category: 'iphone',
    displayName: 'iPhone 17 Pro',
    bezelStyle: 'dynamic-island',
    resolution: { width: 1206, height: 2622 },
    aspectRatio: 1206 / 2622,
    cornerRadiusPct: 12,
    cutout: { widthPct: 29, heightPct: 3.5, topOffsetPct: 2.2 },
    generation: '17',
  },
  {
    id: 'iphone-17-air',
    category: 'iphone',
    displayName: 'iPhone 17 Air',
    bezelStyle: 'dynamic-island',
    resolution: { width: 1260, height: 2736 },
    aspectRatio: 1260 / 2736,
    cornerRadiusPct: 12,
    cutout: { widthPct: 28.5, heightPct: 3.45, topOffsetPct: 2.2 },
    generation: '17',
  },
  {
    id: 'iphone-17',
    category: 'iphone',
    displayName: 'iPhone 17',
    bezelStyle: 'dynamic-island',
    resolution: { width: 1206, height: 2622 },
    aspectRatio: 1206 / 2622,
    cornerRadiusPct: 12,
    cutout: { widthPct: 29, heightPct: 3.5, topOffsetPct: 2.2 },
    generation: '17',
  },

  // --- iPhone 16 line (Dynamic Island) ---
  {
    id: 'iphone-16-pro-max',
    category: 'iphone',
    displayName: 'iPhone 16 Pro Max',
    bezelStyle: 'dynamic-island',
    resolution: { width: 1320, height: 2868 },
    aspectRatio: 1320 / 2868,
    cornerRadiusPct: 12,
    cutout: { widthPct: 28, heightPct: 3.4, topOffsetPct: 2.2 },
    generation: '16',
  },
  {
    id: 'iphone-16-pro',
    category: 'iphone',
    displayName: 'iPhone 16 Pro',
    bezelStyle: 'dynamic-island',
    resolution: { width: 1206, height: 2622 },
    aspectRatio: 1206 / 2622,
    cornerRadiusPct: 12,
    cutout: { widthPct: 29, heightPct: 3.5, topOffsetPct: 2.2 },
    generation: '16',
  },
  {
    id: 'iphone-16-plus',
    category: 'iphone',
    displayName: 'iPhone 16 Plus',
    bezelStyle: 'dynamic-island',
    resolution: { width: 1290, height: 2796 },
    aspectRatio: 1290 / 2796,
    cornerRadiusPct: 12,
    cutout: { widthPct: 28.5, heightPct: 3.45, topOffsetPct: 2.2 },
    generation: '16',
  },
  {
    id: 'iphone-16',
    category: 'iphone',
    displayName: 'iPhone 16',
    bezelStyle: 'dynamic-island',
    resolution: { width: 1179, height: 2556 },
    aspectRatio: 1179 / 2556,
    cornerRadiusPct: 12,
    cutout: { widthPct: 29.5, heightPct: 3.5, topOffsetPct: 2.2 },
    generation: '16',
  },

  // --- iPhone 15 line (Dynamic Island) ---
  {
    id: 'iphone-15-pro-max',
    category: 'iphone',
    displayName: 'iPhone 15 Pro Max',
    bezelStyle: 'dynamic-island',
    resolution: { width: 1290, height: 2796 },
    aspectRatio: 1290 / 2796,
    cornerRadiusPct: 12,
    cutout: { widthPct: 28.5, heightPct: 3.45, topOffsetPct: 2.2 },
    generation: '15',
  },
  {
    id: 'iphone-15-pro',
    category: 'iphone',
    displayName: 'iPhone 15 Pro',
    bezelStyle: 'dynamic-island',
    resolution: { width: 1179, height: 2556 },
    aspectRatio: 1179 / 2556,
    cornerRadiusPct: 12,
    cutout: { widthPct: 29.5, heightPct: 3.5, topOffsetPct: 2.2 },
    generation: '15',
  },
  {
    id: 'iphone-15-plus',
    category: 'iphone',
    displayName: 'iPhone 15 Plus',
    bezelStyle: 'dynamic-island',
    resolution: { width: 1290, height: 2796 },
    aspectRatio: 1290 / 2796,
    cornerRadiusPct: 12,
    cutout: { widthPct: 28.5, heightPct: 3.45, topOffsetPct: 2.2 },
    generation: '15',
  },
  {
    id: 'iphone-15',
    category: 'iphone',
    displayName: 'iPhone 15',
    bezelStyle: 'dynamic-island',
    resolution: { width: 1179, height: 2556 },
    aspectRatio: 1179 / 2556,
    cornerRadiusPct: 12,
    cutout: { widthPct: 29.5, heightPct: 3.5, topOffsetPct: 2.2 },
    generation: '15',
  },

  // --- iPhone 14 Pro (Dynamic Island — first gen) ---
  {
    id: 'iphone-14-pro-max',
    category: 'iphone',
    displayName: 'iPhone 14 Pro Max',
    bezelStyle: 'dynamic-island',
    resolution: { width: 1290, height: 2796 },
    aspectRatio: 1290 / 2796,
    cornerRadiusPct: 12,
    cutout: { widthPct: 28.5, heightPct: 3.45, topOffsetPct: 2.2 },
    generation: '14 Pro',
  },
  {
    id: 'iphone-14-pro',
    category: 'iphone',
    displayName: 'iPhone 14 Pro',
    bezelStyle: 'dynamic-island',
    resolution: { width: 1179, height: 2556 },
    aspectRatio: 1179 / 2556,
    cornerRadiusPct: 12,
    cutout: { widthPct: 29.5, heightPct: 3.5, topOffsetPct: 2.2 },
    generation: '14 Pro',
  },

  // --- Budget / e-series (Notch) ---
  {
    id: 'iphone-17e',
    category: 'iphone',
    displayName: 'iPhone 17e',
    bezelStyle: 'notch',
    resolution: { width: 1170, height: 2532 },
    aspectRatio: 1170 / 2532,
    cornerRadiusPct: 11,
    cutout: { widthPct: 35, heightPct: 3.5, topOffsetPct: 0 },
    generation: '17e',
  },
  {
    id: 'iphone-16e',
    category: 'iphone',
    displayName: 'iPhone 16e',
    bezelStyle: 'notch',
    resolution: { width: 1170, height: 2532 },
    aspectRatio: 1170 / 2532,
    cornerRadiusPct: 11,
    cutout: { widthPct: 35, heightPct: 3.5, topOffsetPct: 0 },
    generation: '16e',
  },

  // --- iPhone 14 / 14 Plus (Notch) ---
  {
    id: 'iphone-14',
    category: 'iphone',
    displayName: 'iPhone 14',
    bezelStyle: 'notch',
    resolution: { width: 1170, height: 2532 },
    aspectRatio: 1170 / 2532,
    cornerRadiusPct: 11,
    cutout: { widthPct: 35, heightPct: 3.5, topOffsetPct: 0 },
    generation: '14',
  },
  {
    id: 'iphone-14-plus',
    category: 'iphone',
    displayName: 'iPhone 14 Plus',
    bezelStyle: 'notch',
    resolution: { width: 1284, height: 2778 },
    aspectRatio: 1284 / 2778,
    cornerRadiusPct: 11,
    cutout: { widthPct: 33, heightPct: 3.3, topOffsetPct: 0 },
    generation: '14',
  },

  // --- iPhone SE (Home button) ---
  {
    id: 'iphone-se-3',
    category: 'iphone',
    displayName: 'iPhone SE (3rd gen)',
    bezelStyle: 'home-button',
    resolution: { width: 750, height: 1334 },
    aspectRatio: 750 / 1334,
    cornerRadiusPct: 4,
    generation: 'SE',
  },
];
